#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quanlysuco")]
	public partial class QLSCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertRole(Role instance);
    partial void UpdateRole(Role instance);
    partial void DeleteRole(Role instance);
    partial void InsertQLSC_NGUOIDUNG(QLSC_NGUOIDUNG instance);
    partial void UpdateQLSC_NGUOIDUNG(QLSC_NGUOIDUNG instance);
    partial void DeleteQLSC_NGUOIDUNG(QLSC_NGUOIDUNG instance);
    partial void InsertQLSC_TAPTIN(QLSC_TAPTIN instance);
    partial void UpdateQLSC_TAPTIN(QLSC_TAPTIN instance);
    partial void DeleteQLSC_TAPTIN(QLSC_TAPTIN instance);
    partial void InsertQLSC_DONVI(QLSC_DONVI instance);
    partial void UpdateQLSC_DONVI(QLSC_DONVI instance);
    partial void DeleteQLSC_DONVI(QLSC_DONVI instance);
    partial void InsertQLSC_LOAISUCO(QLSC_LOAISUCO instance);
    partial void UpdateQLSC_LOAISUCO(QLSC_LOAISUCO instance);
    partial void DeleteQLSC_LOAISUCO(QLSC_LOAISUCO instance);
    partial void InsertQLSC_SUCO(QLSC_SUCO instance);
    partial void UpdateQLSC_SUCO(QLSC_SUCO instance);
    partial void DeleteQLSC_SUCO(QLSC_SUCO instance);
    #endregion
		
		public QLSCDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLSCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<QLSC_NGUOIDUNG> QLSC_NGUOIDUNGs
		{
			get
			{
				return this.GetTable<QLSC_NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<QLSC_TAPTIN> QLSC_TAPTINs
		{
			get
			{
				return this.GetTable<QLSC_TAPTIN>();
			}
		}
		
		public System.Data.Linq.Table<QLSC_DONVI> QLSC_DONVIs
		{
			get
			{
				return this.GetTable<QLSC_DONVI>();
			}
		}
		
		public System.Data.Linq.Table<QLSC_LOAISUCO> QLSC_LOAISUCOs
		{
			get
			{
				return this.GetTable<QLSC_LOAISUCO>();
			}
		}
		
		public System.Data.Linq.Table<QLSC_SUCO> QLSC_SUCOs
		{
			get
			{
				return this.GetTable<QLSC_SUCO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Username;
		
		private string _FirstName;
		
		private string _LastName;
		
		private bool _IsSuperUser;
		
		private System.Nullable<int> _AffiliateId;
		
		private string _Email;
		
		private string _DisplayName;
		
		private bool _UpdatePassword;
		
		private string _LastIPAddress;
		
		private bool _IsDeleted;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private System.Nullable<System.Guid> _PasswordResetToken;
		
		private System.Nullable<System.DateTime> _PasswordResetExpiration;
		
		private string _LowerEmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnIsSuperUserChanging(bool value);
    partial void OnIsSuperUserChanged();
    partial void OnAffiliateIdChanging(System.Nullable<int> value);
    partial void OnAffiliateIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnUpdatePasswordChanging(bool value);
    partial void OnUpdatePasswordChanged();
    partial void OnLastIPAddressChanging(string value);
    partial void OnLastIPAddressChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    partial void OnPasswordResetTokenChanging(System.Nullable<System.Guid> value);
    partial void OnPasswordResetTokenChanged();
    partial void OnPasswordResetExpirationChanging(System.Nullable<System.DateTime> value);
    partial void OnPasswordResetExpirationChanged();
    partial void OnLowerEmailChanging(string value);
    partial void OnLowerEmailChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSuperUser", DbType="Bit NOT NULL")]
		public bool IsSuperUser
		{
			get
			{
				return this._IsSuperUser;
			}
			set
			{
				if ((this._IsSuperUser != value))
				{
					this.OnIsSuperUserChanging(value);
					this.SendPropertyChanging();
					this._IsSuperUser = value;
					this.SendPropertyChanged("IsSuperUser");
					this.OnIsSuperUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AffiliateId", DbType="Int")]
		public System.Nullable<int> AffiliateId
		{
			get
			{
				return this._AffiliateId;
			}
			set
			{
				if ((this._AffiliateId != value))
				{
					this.OnAffiliateIdChanging(value);
					this.SendPropertyChanging();
					this._AffiliateId = value;
					this.SendPropertyChanged("AffiliateId");
					this.OnAffiliateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatePassword", DbType="Bit NOT NULL")]
		public bool UpdatePassword
		{
			get
			{
				return this._UpdatePassword;
			}
			set
			{
				if ((this._UpdatePassword != value))
				{
					this.OnUpdatePasswordChanging(value);
					this.SendPropertyChanging();
					this._UpdatePassword = value;
					this.SendPropertyChanged("UpdatePassword");
					this.OnUpdatePasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastIPAddress", DbType="NVarChar(50)")]
		public string LastIPAddress
		{
			get
			{
				return this._LastIPAddress;
			}
			set
			{
				if ((this._LastIPAddress != value))
				{
					this.OnLastIPAddressChanging(value);
					this.SendPropertyChanging();
					this._LastIPAddress = value;
					this.SendPropertyChanged("LastIPAddress");
					this.OnLastIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordResetToken", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> PasswordResetToken
		{
			get
			{
				return this._PasswordResetToken;
			}
			set
			{
				if ((this._PasswordResetToken != value))
				{
					this.OnPasswordResetTokenChanging(value);
					this.SendPropertyChanging();
					this._PasswordResetToken = value;
					this.SendPropertyChanged("PasswordResetToken");
					this.OnPasswordResetTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordResetExpiration", DbType="DateTime")]
		public System.Nullable<System.DateTime> PasswordResetExpiration
		{
			get
			{
				return this._PasswordResetExpiration;
			}
			set
			{
				if ((this._PasswordResetExpiration != value))
				{
					this.OnPasswordResetExpirationChanging(value);
					this.SendPropertyChanging();
					this._PasswordResetExpiration = value;
					this.SendPropertyChanged("PasswordResetExpiration");
					this.OnPasswordResetExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowerEmail", AutoSync=AutoSync.Always, DbType="NVarChar(256)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string LowerEmail
		{
			get
			{
				return this._LowerEmail;
			}
			set
			{
				if ((this._LowerEmail != value))
				{
					this.OnLowerEmailChanging(value);
					this.SendPropertyChanging();
					this._LowerEmail = value;
					this.SendPropertyChanged("LowerEmail");
					this.OnLowerEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private System.Nullable<int> _PortalID;
		
		private string _RoleName;
		
		private string _Description;
		
		private System.Nullable<decimal> _ServiceFee;
		
		private System.Nullable<char> _BillingFrequency;
		
		private System.Nullable<int> _TrialPeriod;
		
		private System.Nullable<char> _TrialFrequency;
		
		private System.Nullable<int> _BillingPeriod;
		
		private System.Nullable<decimal> _TrialFee;
		
		private bool _IsPublic;
		
		private bool _AutoAssignment;
		
		private System.Nullable<int> _RoleGroupID;
		
		private string _RSVPCode;
		
		private string _IconFile;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private int _Status;
		
		private int _SecurityMode;
		
		private bool _IsSystemRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnPortalIDChanging(System.Nullable<int> value);
    partial void OnPortalIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnServiceFeeChanging(System.Nullable<decimal> value);
    partial void OnServiceFeeChanged();
    partial void OnBillingFrequencyChanging(System.Nullable<char> value);
    partial void OnBillingFrequencyChanged();
    partial void OnTrialPeriodChanging(System.Nullable<int> value);
    partial void OnTrialPeriodChanged();
    partial void OnTrialFrequencyChanging(System.Nullable<char> value);
    partial void OnTrialFrequencyChanged();
    partial void OnBillingPeriodChanging(System.Nullable<int> value);
    partial void OnBillingPeriodChanged();
    partial void OnTrialFeeChanging(System.Nullable<decimal> value);
    partial void OnTrialFeeChanged();
    partial void OnIsPublicChanging(bool value);
    partial void OnIsPublicChanged();
    partial void OnAutoAssignmentChanging(bool value);
    partial void OnAutoAssignmentChanged();
    partial void OnRoleGroupIDChanging(System.Nullable<int> value);
    partial void OnRoleGroupIDChanged();
    partial void OnRSVPCodeChanging(string value);
    partial void OnRSVPCodeChanged();
    partial void OnIconFileChanging(string value);
    partial void OnIconFileChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnSecurityModeChanging(int value);
    partial void OnSecurityModeChanged();
    partial void OnIsSystemRoleChanging(bool value);
    partial void OnIsSystemRoleChanged();
    #endregion
		
		public Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceFee", DbType="Money")]
		public System.Nullable<decimal> ServiceFee
		{
			get
			{
				return this._ServiceFee;
			}
			set
			{
				if ((this._ServiceFee != value))
				{
					this.OnServiceFeeChanging(value);
					this.SendPropertyChanging();
					this._ServiceFee = value;
					this.SendPropertyChanged("ServiceFee");
					this.OnServiceFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingFrequency", DbType="Char(1)")]
		public System.Nullable<char> BillingFrequency
		{
			get
			{
				return this._BillingFrequency;
			}
			set
			{
				if ((this._BillingFrequency != value))
				{
					this.OnBillingFrequencyChanging(value);
					this.SendPropertyChanging();
					this._BillingFrequency = value;
					this.SendPropertyChanged("BillingFrequency");
					this.OnBillingFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrialPeriod", DbType="Int")]
		public System.Nullable<int> TrialPeriod
		{
			get
			{
				return this._TrialPeriod;
			}
			set
			{
				if ((this._TrialPeriod != value))
				{
					this.OnTrialPeriodChanging(value);
					this.SendPropertyChanging();
					this._TrialPeriod = value;
					this.SendPropertyChanged("TrialPeriod");
					this.OnTrialPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrialFrequency", DbType="Char(1)")]
		public System.Nullable<char> TrialFrequency
		{
			get
			{
				return this._TrialFrequency;
			}
			set
			{
				if ((this._TrialFrequency != value))
				{
					this.OnTrialFrequencyChanging(value);
					this.SendPropertyChanging();
					this._TrialFrequency = value;
					this.SendPropertyChanged("TrialFrequency");
					this.OnTrialFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingPeriod", DbType="Int")]
		public System.Nullable<int> BillingPeriod
		{
			get
			{
				return this._BillingPeriod;
			}
			set
			{
				if ((this._BillingPeriod != value))
				{
					this.OnBillingPeriodChanging(value);
					this.SendPropertyChanging();
					this._BillingPeriod = value;
					this.SendPropertyChanged("BillingPeriod");
					this.OnBillingPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrialFee", DbType="Money")]
		public System.Nullable<decimal> TrialFee
		{
			get
			{
				return this._TrialFee;
			}
			set
			{
				if ((this._TrialFee != value))
				{
					this.OnTrialFeeChanging(value);
					this.SendPropertyChanging();
					this._TrialFee = value;
					this.SendPropertyChanged("TrialFee");
					this.OnTrialFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublic", DbType="Bit NOT NULL")]
		public bool IsPublic
		{
			get
			{
				return this._IsPublic;
			}
			set
			{
				if ((this._IsPublic != value))
				{
					this.OnIsPublicChanging(value);
					this.SendPropertyChanging();
					this._IsPublic = value;
					this.SendPropertyChanged("IsPublic");
					this.OnIsPublicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoAssignment", DbType="Bit NOT NULL")]
		public bool AutoAssignment
		{
			get
			{
				return this._AutoAssignment;
			}
			set
			{
				if ((this._AutoAssignment != value))
				{
					this.OnAutoAssignmentChanging(value);
					this.SendPropertyChanging();
					this._AutoAssignment = value;
					this.SendPropertyChanged("AutoAssignment");
					this.OnAutoAssignmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleGroupID", DbType="Int")]
		public System.Nullable<int> RoleGroupID
		{
			get
			{
				return this._RoleGroupID;
			}
			set
			{
				if ((this._RoleGroupID != value))
				{
					this.OnRoleGroupIDChanging(value);
					this.SendPropertyChanging();
					this._RoleGroupID = value;
					this.SendPropertyChanged("RoleGroupID");
					this.OnRoleGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSVPCode", DbType="NVarChar(50)")]
		public string RSVPCode
		{
			get
			{
				return this._RSVPCode;
			}
			set
			{
				if ((this._RSVPCode != value))
				{
					this.OnRSVPCodeChanging(value);
					this.SendPropertyChanging();
					this._RSVPCode = value;
					this.SendPropertyChanged("RSVPCode");
					this.OnRSVPCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFile", DbType="NVarChar(100)")]
		public string IconFile
		{
			get
			{
				return this._IconFile;
			}
			set
			{
				if ((this._IconFile != value))
				{
					this.OnIconFileChanging(value);
					this.SendPropertyChanging();
					this._IconFile = value;
					this.SendPropertyChanged("IconFile");
					this.OnIconFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityMode", DbType="Int NOT NULL")]
		public int SecurityMode
		{
			get
			{
				return this._SecurityMode;
			}
			set
			{
				if ((this._SecurityMode != value))
				{
					this.OnSecurityModeChanging(value);
					this.SendPropertyChanging();
					this._SecurityMode = value;
					this.SendPropertyChanged("SecurityMode");
					this.OnSecurityModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSystemRole", DbType="Bit NOT NULL")]
		public bool IsSystemRole
		{
			get
			{
				return this._IsSystemRole;
			}
			set
			{
				if ((this._IsSystemRole != value))
				{
					this.OnIsSystemRoleChanging(value);
					this.SendPropertyChanging();
					this._IsSystemRole = value;
					this.SendPropertyChanged("IsSystemRole");
					this.OnIsSystemRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLSC_NGUOIDUNG")]
	public partial class QLSC_NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ND_ID;
		
		private string _ND_TEN;
		
		private string _UserName;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<int> _RoleID;
		
		private int _DONVI_ID;
		
		private string _ND_GHICHU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnND_IDChanging(int value);
    partial void OnND_IDChanged();
    partial void OnND_TENChanging(string value);
    partial void OnND_TENChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnRoleIDChanging(System.Nullable<int> value);
    partial void OnRoleIDChanged();
    partial void OnDONVI_IDChanging(int value);
    partial void OnDONVI_IDChanged();
    partial void OnND_GHICHUChanging(string value);
    partial void OnND_GHICHUChanged();
    #endregion
		
		public QLSC_NGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ND_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ND_ID
		{
			get
			{
				return this._ND_ID;
			}
			set
			{
				if ((this._ND_ID != value))
				{
					this.OnND_IDChanging(value);
					this.SendPropertyChanging();
					this._ND_ID = value;
					this.SendPropertyChanged("ND_ID");
					this.OnND_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ND_TEN", DbType="NVarChar(128)")]
		public string ND_TEN
		{
			get
			{
				return this._ND_TEN;
			}
			set
			{
				if ((this._ND_TEN != value))
				{
					this.OnND_TENChanging(value);
					this.SendPropertyChanging();
					this._ND_TEN = value;
					this.SendPropertyChanged("ND_TEN");
					this.OnND_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int")]
		public System.Nullable<int> RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_ID", DbType="Int NOT NULL")]
		public int DONVI_ID
		{
			get
			{
				return this._DONVI_ID;
			}
			set
			{
				if ((this._DONVI_ID != value))
				{
					this.OnDONVI_IDChanging(value);
					this.SendPropertyChanging();
					this._DONVI_ID = value;
					this.SendPropertyChanged("DONVI_ID");
					this.OnDONVI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ND_GHICHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ND_GHICHU
		{
			get
			{
				return this._ND_GHICHU;
			}
			set
			{
				if ((this._ND_GHICHU != value))
				{
					this.OnND_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._ND_GHICHU = value;
					this.SendPropertyChanged("ND_GHICHU");
					this.OnND_GHICHUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLSC_TAPTIN")]
	public partial class QLSC_TAPTIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FILE_ID;
		
		private string _FILE_NAME;
		
		private string _FILE_MOTA;
		
		private string _FILE_EXT;
		
		private int _FILE_SIZE;
		
		private int _FILE_USERID_CAPNHAT;
		
		private System.DateTime _FILE_NGAYCAPNHAT;
		
		private int _OBJECT_LOAI;
		
		private int _OBJECT_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFILE_IDChanging(int value);
    partial void OnFILE_IDChanged();
    partial void OnFILE_NAMEChanging(string value);
    partial void OnFILE_NAMEChanged();
    partial void OnFILE_MOTAChanging(string value);
    partial void OnFILE_MOTAChanged();
    partial void OnFILE_EXTChanging(string value);
    partial void OnFILE_EXTChanged();
    partial void OnFILE_SIZEChanging(int value);
    partial void OnFILE_SIZEChanged();
    partial void OnFILE_USERID_CAPNHATChanging(int value);
    partial void OnFILE_USERID_CAPNHATChanged();
    partial void OnFILE_NGAYCAPNHATChanging(System.DateTime value);
    partial void OnFILE_NGAYCAPNHATChanged();
    partial void OnOBJECT_LOAIChanging(int value);
    partial void OnOBJECT_LOAIChanged();
    partial void OnOBJECT_IDChanging(int value);
    partial void OnOBJECT_IDChanged();
    #endregion
		
		public QLSC_TAPTIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FILE_ID
		{
			get
			{
				return this._FILE_ID;
			}
			set
			{
				if ((this._FILE_ID != value))
				{
					this.OnFILE_IDChanging(value);
					this.SendPropertyChanging();
					this._FILE_ID = value;
					this.SendPropertyChanged("FILE_ID");
					this.OnFILE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NAME", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FILE_NAME
		{
			get
			{
				return this._FILE_NAME;
			}
			set
			{
				if ((this._FILE_NAME != value))
				{
					this.OnFILE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FILE_NAME = value;
					this.SendPropertyChanged("FILE_NAME");
					this.OnFILE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_MOTA", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FILE_MOTA
		{
			get
			{
				return this._FILE_MOTA;
			}
			set
			{
				if ((this._FILE_MOTA != value))
				{
					this.OnFILE_MOTAChanging(value);
					this.SendPropertyChanging();
					this._FILE_MOTA = value;
					this.SendPropertyChanged("FILE_MOTA");
					this.OnFILE_MOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_EXT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string FILE_EXT
		{
			get
			{
				return this._FILE_EXT;
			}
			set
			{
				if ((this._FILE_EXT != value))
				{
					this.OnFILE_EXTChanging(value);
					this.SendPropertyChanging();
					this._FILE_EXT = value;
					this.SendPropertyChanged("FILE_EXT");
					this.OnFILE_EXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_SIZE", DbType="Int NOT NULL")]
		public int FILE_SIZE
		{
			get
			{
				return this._FILE_SIZE;
			}
			set
			{
				if ((this._FILE_SIZE != value))
				{
					this.OnFILE_SIZEChanging(value);
					this.SendPropertyChanging();
					this._FILE_SIZE = value;
					this.SendPropertyChanged("FILE_SIZE");
					this.OnFILE_SIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_USERID_CAPNHAT", DbType="Int NOT NULL")]
		public int FILE_USERID_CAPNHAT
		{
			get
			{
				return this._FILE_USERID_CAPNHAT;
			}
			set
			{
				if ((this._FILE_USERID_CAPNHAT != value))
				{
					this.OnFILE_USERID_CAPNHATChanging(value);
					this.SendPropertyChanging();
					this._FILE_USERID_CAPNHAT = value;
					this.SendPropertyChanged("FILE_USERID_CAPNHAT");
					this.OnFILE_USERID_CAPNHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NGAYCAPNHAT", DbType="DateTime NOT NULL")]
		public System.DateTime FILE_NGAYCAPNHAT
		{
			get
			{
				return this._FILE_NGAYCAPNHAT;
			}
			set
			{
				if ((this._FILE_NGAYCAPNHAT != value))
				{
					this.OnFILE_NGAYCAPNHATChanging(value);
					this.SendPropertyChanging();
					this._FILE_NGAYCAPNHAT = value;
					this.SendPropertyChanged("FILE_NGAYCAPNHAT");
					this.OnFILE_NGAYCAPNHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECT_LOAI", DbType="Int NOT NULL")]
		public int OBJECT_LOAI
		{
			get
			{
				return this._OBJECT_LOAI;
			}
			set
			{
				if ((this._OBJECT_LOAI != value))
				{
					this.OnOBJECT_LOAIChanging(value);
					this.SendPropertyChanging();
					this._OBJECT_LOAI = value;
					this.SendPropertyChanged("OBJECT_LOAI");
					this.OnOBJECT_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECT_ID", DbType="Int NOT NULL")]
		public int OBJECT_ID
		{
			get
			{
				return this._OBJECT_ID;
			}
			set
			{
				if ((this._OBJECT_ID != value))
				{
					this.OnOBJECT_IDChanging(value);
					this.SendPropertyChanging();
					this._OBJECT_ID = value;
					this.SendPropertyChanged("OBJECT_ID");
					this.OnOBJECT_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLSC_DONVI")]
	public partial class QLSC_DONVI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DONVI_ID;
		
		private string _DONVI_TEN;
		
		private string _DONVI_GHICHU;
		
		private System.Nullable<int> _DONVI_ROLE_ID;
		
		private string _DONVI_TENRUTGON;
		
		private EntitySet<QLSC_SUCO> _QLSC_SUCOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDONVI_IDChanging(int value);
    partial void OnDONVI_IDChanged();
    partial void OnDONVI_TENChanging(string value);
    partial void OnDONVI_TENChanged();
    partial void OnDONVI_GHICHUChanging(string value);
    partial void OnDONVI_GHICHUChanged();
    partial void OnDONVI_ROLE_IDChanging(System.Nullable<int> value);
    partial void OnDONVI_ROLE_IDChanged();
    partial void OnDONVI_TENRUTGONChanging(string value);
    partial void OnDONVI_TENRUTGONChanged();
    #endregion
		
		public QLSC_DONVI()
		{
			this._QLSC_SUCOs = new EntitySet<QLSC_SUCO>(new Action<QLSC_SUCO>(this.attach_QLSC_SUCOs), new Action<QLSC_SUCO>(this.detach_QLSC_SUCOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DONVI_ID
		{
			get
			{
				return this._DONVI_ID;
			}
			set
			{
				if ((this._DONVI_ID != value))
				{
					this.OnDONVI_IDChanging(value);
					this.SendPropertyChanging();
					this._DONVI_ID = value;
					this.SendPropertyChanged("DONVI_ID");
					this.OnDONVI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_TEN", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DONVI_TEN
		{
			get
			{
				return this._DONVI_TEN;
			}
			set
			{
				if ((this._DONVI_TEN != value))
				{
					this.OnDONVI_TENChanging(value);
					this.SendPropertyChanging();
					this._DONVI_TEN = value;
					this.SendPropertyChanged("DONVI_TEN");
					this.OnDONVI_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_GHICHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DONVI_GHICHU
		{
			get
			{
				return this._DONVI_GHICHU;
			}
			set
			{
				if ((this._DONVI_GHICHU != value))
				{
					this.OnDONVI_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._DONVI_GHICHU = value;
					this.SendPropertyChanged("DONVI_GHICHU");
					this.OnDONVI_GHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_ROLE_ID", DbType="Int")]
		public System.Nullable<int> DONVI_ROLE_ID
		{
			get
			{
				return this._DONVI_ROLE_ID;
			}
			set
			{
				if ((this._DONVI_ROLE_ID != value))
				{
					this.OnDONVI_ROLE_IDChanging(value);
					this.SendPropertyChanging();
					this._DONVI_ROLE_ID = value;
					this.SendPropertyChanged("DONVI_ROLE_ID");
					this.OnDONVI_ROLE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_TENRUTGON", DbType="NVarChar(100)")]
		public string DONVI_TENRUTGON
		{
			get
			{
				return this._DONVI_TENRUTGON;
			}
			set
			{
				if ((this._DONVI_TENRUTGON != value))
				{
					this.OnDONVI_TENRUTGONChanging(value);
					this.SendPropertyChanging();
					this._DONVI_TENRUTGON = value;
					this.SendPropertyChanged("DONVI_TENRUTGON");
					this.OnDONVI_TENRUTGONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLSC_DONVI_QLSC_SUCO", Storage="_QLSC_SUCOs", ThisKey="DONVI_ID", OtherKey="DONVI_ID")]
		public EntitySet<QLSC_SUCO> QLSC_SUCOs
		{
			get
			{
				return this._QLSC_SUCOs;
			}
			set
			{
				this._QLSC_SUCOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QLSC_SUCOs(QLSC_SUCO entity)
		{
			this.SendPropertyChanging();
			entity.QLSC_DONVI = this;
		}
		
		private void detach_QLSC_SUCOs(QLSC_SUCO entity)
		{
			this.SendPropertyChanging();
			entity.QLSC_DONVI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLSC_LOAISUCO")]
	public partial class QLSC_LOAISUCO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LOAISC_ID;
		
		private string _LOAISC_TEN;
		
		private string _LOAISC_GHICHU;
		
		private EntitySet<QLSC_SUCO> _QLSC_SUCOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOAISC_IDChanging(int value);
    partial void OnLOAISC_IDChanged();
    partial void OnLOAISC_TENChanging(string value);
    partial void OnLOAISC_TENChanged();
    partial void OnLOAISC_GHICHUChanging(string value);
    partial void OnLOAISC_GHICHUChanged();
    #endregion
		
		public QLSC_LOAISUCO()
		{
			this._QLSC_SUCOs = new EntitySet<QLSC_SUCO>(new Action<QLSC_SUCO>(this.attach_QLSC_SUCOs), new Action<QLSC_SUCO>(this.detach_QLSC_SUCOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LOAISC_ID
		{
			get
			{
				return this._LOAISC_ID;
			}
			set
			{
				if ((this._LOAISC_ID != value))
				{
					this.OnLOAISC_IDChanging(value);
					this.SendPropertyChanging();
					this._LOAISC_ID = value;
					this.SendPropertyChanged("LOAISC_ID");
					this.OnLOAISC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISC_TEN", DbType="NVarChar(1000)")]
		public string LOAISC_TEN
		{
			get
			{
				return this._LOAISC_TEN;
			}
			set
			{
				if ((this._LOAISC_TEN != value))
				{
					this.OnLOAISC_TENChanging(value);
					this.SendPropertyChanging();
					this._LOAISC_TEN = value;
					this.SendPropertyChanged("LOAISC_TEN");
					this.OnLOAISC_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISC_GHICHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LOAISC_GHICHU
		{
			get
			{
				return this._LOAISC_GHICHU;
			}
			set
			{
				if ((this._LOAISC_GHICHU != value))
				{
					this.OnLOAISC_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._LOAISC_GHICHU = value;
					this.SendPropertyChanged("LOAISC_GHICHU");
					this.OnLOAISC_GHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLSC_LOAISUCO_QLSC_SUCO", Storage="_QLSC_SUCOs", ThisKey="LOAISC_ID", OtherKey="LOAISC_ID")]
		public EntitySet<QLSC_SUCO> QLSC_SUCOs
		{
			get
			{
				return this._QLSC_SUCOs;
			}
			set
			{
				this._QLSC_SUCOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QLSC_SUCOs(QLSC_SUCO entity)
		{
			this.SendPropertyChanging();
			entity.QLSC_LOAISUCO = this;
		}
		
		private void detach_QLSC_SUCOs(QLSC_SUCO entity)
		{
			this.SendPropertyChanging();
			entity.QLSC_LOAISUCO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLSC_SUCO")]
	public partial class QLSC_SUCO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SC_ID;
		
		private string _SC_Date;
		
		private System.Nullable<System.DateTime> _SC_NGAYXAYRA;
		
		private System.Nullable<System.DateTime> _SC_NGAYTAILAP;
		
		private string _SC_NOIDUNG;
		
		private string _SC_NGUYENNHAN;
		
		private string _SC_VTTB_TENCHUNGLOAI;
		
		private System.Nullable<int> _SC_VTTB_SOLUONG;
		
		private string _SC_VTTB_NHASANXUAT;
		
		private string _SC_VTTB_NAMVANHANH;
		
		private System.Nullable<int> _SC_DIENAP;
		
		private System.Nullable<int> _SC_CQ;
		
		private System.Nullable<int> _SC_KQ;
		
		private System.Nullable<int> _SC_LOAI;
		
		private System.Nullable<int> _SC_TONGSOKH;
		
		private System.Nullable<int> _SC_TAISAN;
		
		private string _SC_GHICHU;
		
		private System.Nullable<int> _UserID;
		
		private int _DONVI_ID;
		
		private int _LOAISC_ID;
		
		private string _SC_VTTB_TENCHUNGLOAI2;
		
		private System.Nullable<int> _SC_VTTB_SOLUONG2;
		
		private string _SC_VTTB_NHASANXUAT2;
		
		private string _SC_VTTB_NAMVANHANH2;
		
		private string _SC_VTTB_TENCHUNGLOAI3;
		
		private System.Nullable<int> _SC_VTTB_SOLUONG3;
		
		private string _SC_VTTB_NHASANXUAT3;
		
		private string _SC_VTTB_NAMVANHANH3;
		
		private string _SC_VTTB_TENCHUNGLOAI4;
		
		private System.Nullable<int> _SC_VTTB_SOLUONG4;
		
		private string _SC_VTTB_NHASANXUAT4;
		
		private string _SC_VTTB_NAMVANHANH4;
		
		private string _SC_VTTB_TENCHUNGLOAI5;
		
		private System.Nullable<int> _SC_VTTB_SOLUONG5;
		
		private string _SC_VTTB_NHASANXUAT5;
		
		private string _SC_VTTB_NAMVANHANH5;
		
		private string _SC_THIETBIDONGCAT_MSRCS;
		
		private EntityRef<QLSC_DONVI> _QLSC_DONVI;
		
		private EntityRef<QLSC_LOAISUCO> _QLSC_LOAISUCO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSC_IDChanging(int value);
    partial void OnSC_IDChanged();
    partial void OnSC_DateChanging(string value);
    partial void OnSC_DateChanged();
    partial void OnSC_NGAYXAYRAChanging(System.Nullable<System.DateTime> value);
    partial void OnSC_NGAYXAYRAChanged();
    partial void OnSC_NGAYTAILAPChanging(System.Nullable<System.DateTime> value);
    partial void OnSC_NGAYTAILAPChanged();
    partial void OnSC_NOIDUNGChanging(string value);
    partial void OnSC_NOIDUNGChanged();
    partial void OnSC_NGUYENNHANChanging(string value);
    partial void OnSC_NGUYENNHANChanged();
    partial void OnSC_VTTB_TENCHUNGLOAIChanging(string value);
    partial void OnSC_VTTB_TENCHUNGLOAIChanged();
    partial void OnSC_VTTB_SOLUONGChanging(System.Nullable<int> value);
    partial void OnSC_VTTB_SOLUONGChanged();
    partial void OnSC_VTTB_NHASANXUATChanging(string value);
    partial void OnSC_VTTB_NHASANXUATChanged();
    partial void OnSC_VTTB_NAMVANHANHChanging(string value);
    partial void OnSC_VTTB_NAMVANHANHChanged();
    partial void OnSC_DIENAPChanging(System.Nullable<int> value);
    partial void OnSC_DIENAPChanged();
    partial void OnSC_CQChanging(System.Nullable<int> value);
    partial void OnSC_CQChanged();
    partial void OnSC_KQChanging(System.Nullable<int> value);
    partial void OnSC_KQChanged();
    partial void OnSC_LOAIChanging(System.Nullable<int> value);
    partial void OnSC_LOAIChanged();
    partial void OnSC_TONGSOKHChanging(System.Nullable<int> value);
    partial void OnSC_TONGSOKHChanged();
    partial void OnSC_TAISANChanging(System.Nullable<int> value);
    partial void OnSC_TAISANChanged();
    partial void OnSC_GHICHUChanging(string value);
    partial void OnSC_GHICHUChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnDONVI_IDChanging(int value);
    partial void OnDONVI_IDChanged();
    partial void OnLOAISC_IDChanging(int value);
    partial void OnLOAISC_IDChanged();
    partial void OnSC_VTTB_TENCHUNGLOAI2Changing(string value);
    partial void OnSC_VTTB_TENCHUNGLOAI2Changed();
    partial void OnSC_VTTB_SOLUONG2Changing(System.Nullable<int> value);
    partial void OnSC_VTTB_SOLUONG2Changed();
    partial void OnSC_VTTB_NHASANXUAT2Changing(string value);
    partial void OnSC_VTTB_NHASANXUAT2Changed();
    partial void OnSC_VTTB_NAMVANHANH2Changing(string value);
    partial void OnSC_VTTB_NAMVANHANH2Changed();
    partial void OnSC_VTTB_TENCHUNGLOAI3Changing(string value);
    partial void OnSC_VTTB_TENCHUNGLOAI3Changed();
    partial void OnSC_VTTB_SOLUONG3Changing(System.Nullable<int> value);
    partial void OnSC_VTTB_SOLUONG3Changed();
    partial void OnSC_VTTB_NHASANXUAT3Changing(string value);
    partial void OnSC_VTTB_NHASANXUAT3Changed();
    partial void OnSC_VTTB_NAMVANHANH3Changing(string value);
    partial void OnSC_VTTB_NAMVANHANH3Changed();
    partial void OnSC_VTTB_TENCHUNGLOAI4Changing(string value);
    partial void OnSC_VTTB_TENCHUNGLOAI4Changed();
    partial void OnSC_VTTB_SOLUONG4Changing(System.Nullable<int> value);
    partial void OnSC_VTTB_SOLUONG4Changed();
    partial void OnSC_VTTB_NHASANXUAT4Changing(string value);
    partial void OnSC_VTTB_NHASANXUAT4Changed();
    partial void OnSC_VTTB_NAMVANHANH4Changing(string value);
    partial void OnSC_VTTB_NAMVANHANH4Changed();
    partial void OnSC_VTTB_TENCHUNGLOAI5Changing(string value);
    partial void OnSC_VTTB_TENCHUNGLOAI5Changed();
    partial void OnSC_VTTB_SOLUONG5Changing(System.Nullable<int> value);
    partial void OnSC_VTTB_SOLUONG5Changed();
    partial void OnSC_VTTB_NHASANXUAT5Changing(string value);
    partial void OnSC_VTTB_NHASANXUAT5Changed();
    partial void OnSC_VTTB_NAMVANHANH5Changing(string value);
    partial void OnSC_VTTB_NAMVANHANH5Changed();
    partial void OnSC_THIETBIDONGCAT_MSRCSChanging(string value);
    partial void OnSC_THIETBIDONGCAT_MSRCSChanged();
    #endregion
		
		public QLSC_SUCO()
		{
			this._QLSC_DONVI = default(EntityRef<QLSC_DONVI>);
			this._QLSC_LOAISUCO = default(EntityRef<QLSC_LOAISUCO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SC_ID
		{
			get
			{
				return this._SC_ID;
			}
			set
			{
				if ((this._SC_ID != value))
				{
					this.OnSC_IDChanging(value);
					this.SendPropertyChanging();
					this._SC_ID = value;
					this.SendPropertyChanged("SC_ID");
					this.OnSC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_Date", DbType="NChar(10)")]
		public string SC_Date
		{
			get
			{
				return this._SC_Date;
			}
			set
			{
				if ((this._SC_Date != value))
				{
					this.OnSC_DateChanging(value);
					this.SendPropertyChanging();
					this._SC_Date = value;
					this.SendPropertyChanged("SC_Date");
					this.OnSC_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_NGAYXAYRA", DbType="DateTime")]
		public System.Nullable<System.DateTime> SC_NGAYXAYRA
		{
			get
			{
				return this._SC_NGAYXAYRA;
			}
			set
			{
				if ((this._SC_NGAYXAYRA != value))
				{
					this.OnSC_NGAYXAYRAChanging(value);
					this.SendPropertyChanging();
					this._SC_NGAYXAYRA = value;
					this.SendPropertyChanged("SC_NGAYXAYRA");
					this.OnSC_NGAYXAYRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_NGAYTAILAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> SC_NGAYTAILAP
		{
			get
			{
				return this._SC_NGAYTAILAP;
			}
			set
			{
				if ((this._SC_NGAYTAILAP != value))
				{
					this.OnSC_NGAYTAILAPChanging(value);
					this.SendPropertyChanging();
					this._SC_NGAYTAILAP = value;
					this.SendPropertyChanged("SC_NGAYTAILAP");
					this.OnSC_NGAYTAILAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_NOIDUNG", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SC_NOIDUNG
		{
			get
			{
				return this._SC_NOIDUNG;
			}
			set
			{
				if ((this._SC_NOIDUNG != value))
				{
					this.OnSC_NOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._SC_NOIDUNG = value;
					this.SendPropertyChanged("SC_NOIDUNG");
					this.OnSC_NOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_NGUYENNHAN", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SC_NGUYENNHAN
		{
			get
			{
				return this._SC_NGUYENNHAN;
			}
			set
			{
				if ((this._SC_NGUYENNHAN != value))
				{
					this.OnSC_NGUYENNHANChanging(value);
					this.SendPropertyChanging();
					this._SC_NGUYENNHAN = value;
					this.SendPropertyChanged("SC_NGUYENNHAN");
					this.OnSC_NGUYENNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_TENCHUNGLOAI", DbType="NVarChar(500)")]
		public string SC_VTTB_TENCHUNGLOAI
		{
			get
			{
				return this._SC_VTTB_TENCHUNGLOAI;
			}
			set
			{
				if ((this._SC_VTTB_TENCHUNGLOAI != value))
				{
					this.OnSC_VTTB_TENCHUNGLOAIChanging(value);
					this.SendPropertyChanging();
					this._SC_VTTB_TENCHUNGLOAI = value;
					this.SendPropertyChanged("SC_VTTB_TENCHUNGLOAI");
					this.OnSC_VTTB_TENCHUNGLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_SOLUONG", DbType="Int")]
		public System.Nullable<int> SC_VTTB_SOLUONG
		{
			get
			{
				return this._SC_VTTB_SOLUONG;
			}
			set
			{
				if ((this._SC_VTTB_SOLUONG != value))
				{
					this.OnSC_VTTB_SOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SC_VTTB_SOLUONG = value;
					this.SendPropertyChanged("SC_VTTB_SOLUONG");
					this.OnSC_VTTB_SOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NHASANXUAT", DbType="NVarChar(500)")]
		public string SC_VTTB_NHASANXUAT
		{
			get
			{
				return this._SC_VTTB_NHASANXUAT;
			}
			set
			{
				if ((this._SC_VTTB_NHASANXUAT != value))
				{
					this.OnSC_VTTB_NHASANXUATChanging(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NHASANXUAT = value;
					this.SendPropertyChanged("SC_VTTB_NHASANXUAT");
					this.OnSC_VTTB_NHASANXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NAMVANHANH", DbType="NVarChar(10)")]
		public string SC_VTTB_NAMVANHANH
		{
			get
			{
				return this._SC_VTTB_NAMVANHANH;
			}
			set
			{
				if ((this._SC_VTTB_NAMVANHANH != value))
				{
					this.OnSC_VTTB_NAMVANHANHChanging(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NAMVANHANH = value;
					this.SendPropertyChanged("SC_VTTB_NAMVANHANH");
					this.OnSC_VTTB_NAMVANHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_DIENAP", DbType="Int")]
		public System.Nullable<int> SC_DIENAP
		{
			get
			{
				return this._SC_DIENAP;
			}
			set
			{
				if ((this._SC_DIENAP != value))
				{
					this.OnSC_DIENAPChanging(value);
					this.SendPropertyChanging();
					this._SC_DIENAP = value;
					this.SendPropertyChanged("SC_DIENAP");
					this.OnSC_DIENAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_CQ", DbType="Int")]
		public System.Nullable<int> SC_CQ
		{
			get
			{
				return this._SC_CQ;
			}
			set
			{
				if ((this._SC_CQ != value))
				{
					this.OnSC_CQChanging(value);
					this.SendPropertyChanging();
					this._SC_CQ = value;
					this.SendPropertyChanged("SC_CQ");
					this.OnSC_CQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_KQ", DbType="Int")]
		public System.Nullable<int> SC_KQ
		{
			get
			{
				return this._SC_KQ;
			}
			set
			{
				if ((this._SC_KQ != value))
				{
					this.OnSC_KQChanging(value);
					this.SendPropertyChanging();
					this._SC_KQ = value;
					this.SendPropertyChanged("SC_KQ");
					this.OnSC_KQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_LOAI", DbType="Int")]
		public System.Nullable<int> SC_LOAI
		{
			get
			{
				return this._SC_LOAI;
			}
			set
			{
				if ((this._SC_LOAI != value))
				{
					this.OnSC_LOAIChanging(value);
					this.SendPropertyChanging();
					this._SC_LOAI = value;
					this.SendPropertyChanged("SC_LOAI");
					this.OnSC_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_TONGSOKH", DbType="Int")]
		public System.Nullable<int> SC_TONGSOKH
		{
			get
			{
				return this._SC_TONGSOKH;
			}
			set
			{
				if ((this._SC_TONGSOKH != value))
				{
					this.OnSC_TONGSOKHChanging(value);
					this.SendPropertyChanging();
					this._SC_TONGSOKH = value;
					this.SendPropertyChanged("SC_TONGSOKH");
					this.OnSC_TONGSOKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_TAISAN", DbType="Int")]
		public System.Nullable<int> SC_TAISAN
		{
			get
			{
				return this._SC_TAISAN;
			}
			set
			{
				if ((this._SC_TAISAN != value))
				{
					this.OnSC_TAISANChanging(value);
					this.SendPropertyChanging();
					this._SC_TAISAN = value;
					this.SendPropertyChanged("SC_TAISAN");
					this.OnSC_TAISANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_GHICHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string SC_GHICHU
		{
			get
			{
				return this._SC_GHICHU;
			}
			set
			{
				if ((this._SC_GHICHU != value))
				{
					this.OnSC_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._SC_GHICHU = value;
					this.SendPropertyChanged("SC_GHICHU");
					this.OnSC_GHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI_ID", DbType="Int NOT NULL")]
		public int DONVI_ID
		{
			get
			{
				return this._DONVI_ID;
			}
			set
			{
				if ((this._DONVI_ID != value))
				{
					if (this._QLSC_DONVI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDONVI_IDChanging(value);
					this.SendPropertyChanging();
					this._DONVI_ID = value;
					this.SendPropertyChanged("DONVI_ID");
					this.OnDONVI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISC_ID", DbType="Int NOT NULL")]
		public int LOAISC_ID
		{
			get
			{
				return this._LOAISC_ID;
			}
			set
			{
				if ((this._LOAISC_ID != value))
				{
					if (this._QLSC_LOAISUCO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLOAISC_IDChanging(value);
					this.SendPropertyChanging();
					this._LOAISC_ID = value;
					this.SendPropertyChanged("LOAISC_ID");
					this.OnLOAISC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_TENCHUNGLOAI2", DbType="NVarChar(500)")]
		public string SC_VTTB_TENCHUNGLOAI2
		{
			get
			{
				return this._SC_VTTB_TENCHUNGLOAI2;
			}
			set
			{
				if ((this._SC_VTTB_TENCHUNGLOAI2 != value))
				{
					this.OnSC_VTTB_TENCHUNGLOAI2Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_TENCHUNGLOAI2 = value;
					this.SendPropertyChanged("SC_VTTB_TENCHUNGLOAI2");
					this.OnSC_VTTB_TENCHUNGLOAI2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_SOLUONG2", DbType="Int")]
		public System.Nullable<int> SC_VTTB_SOLUONG2
		{
			get
			{
				return this._SC_VTTB_SOLUONG2;
			}
			set
			{
				if ((this._SC_VTTB_SOLUONG2 != value))
				{
					this.OnSC_VTTB_SOLUONG2Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_SOLUONG2 = value;
					this.SendPropertyChanged("SC_VTTB_SOLUONG2");
					this.OnSC_VTTB_SOLUONG2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NHASANXUAT2", DbType="NVarChar(500)")]
		public string SC_VTTB_NHASANXUAT2
		{
			get
			{
				return this._SC_VTTB_NHASANXUAT2;
			}
			set
			{
				if ((this._SC_VTTB_NHASANXUAT2 != value))
				{
					this.OnSC_VTTB_NHASANXUAT2Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NHASANXUAT2 = value;
					this.SendPropertyChanged("SC_VTTB_NHASANXUAT2");
					this.OnSC_VTTB_NHASANXUAT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NAMVANHANH2", DbType="NVarChar(10)")]
		public string SC_VTTB_NAMVANHANH2
		{
			get
			{
				return this._SC_VTTB_NAMVANHANH2;
			}
			set
			{
				if ((this._SC_VTTB_NAMVANHANH2 != value))
				{
					this.OnSC_VTTB_NAMVANHANH2Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NAMVANHANH2 = value;
					this.SendPropertyChanged("SC_VTTB_NAMVANHANH2");
					this.OnSC_VTTB_NAMVANHANH2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_TENCHUNGLOAI3", DbType="NVarChar(500)")]
		public string SC_VTTB_TENCHUNGLOAI3
		{
			get
			{
				return this._SC_VTTB_TENCHUNGLOAI3;
			}
			set
			{
				if ((this._SC_VTTB_TENCHUNGLOAI3 != value))
				{
					this.OnSC_VTTB_TENCHUNGLOAI3Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_TENCHUNGLOAI3 = value;
					this.SendPropertyChanged("SC_VTTB_TENCHUNGLOAI3");
					this.OnSC_VTTB_TENCHUNGLOAI3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_SOLUONG3", DbType="Int")]
		public System.Nullable<int> SC_VTTB_SOLUONG3
		{
			get
			{
				return this._SC_VTTB_SOLUONG3;
			}
			set
			{
				if ((this._SC_VTTB_SOLUONG3 != value))
				{
					this.OnSC_VTTB_SOLUONG3Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_SOLUONG3 = value;
					this.SendPropertyChanged("SC_VTTB_SOLUONG3");
					this.OnSC_VTTB_SOLUONG3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NHASANXUAT3", DbType="NVarChar(500)")]
		public string SC_VTTB_NHASANXUAT3
		{
			get
			{
				return this._SC_VTTB_NHASANXUAT3;
			}
			set
			{
				if ((this._SC_VTTB_NHASANXUAT3 != value))
				{
					this.OnSC_VTTB_NHASANXUAT3Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NHASANXUAT3 = value;
					this.SendPropertyChanged("SC_VTTB_NHASANXUAT3");
					this.OnSC_VTTB_NHASANXUAT3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NAMVANHANH3", DbType="NVarChar(10)")]
		public string SC_VTTB_NAMVANHANH3
		{
			get
			{
				return this._SC_VTTB_NAMVANHANH3;
			}
			set
			{
				if ((this._SC_VTTB_NAMVANHANH3 != value))
				{
					this.OnSC_VTTB_NAMVANHANH3Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NAMVANHANH3 = value;
					this.SendPropertyChanged("SC_VTTB_NAMVANHANH3");
					this.OnSC_VTTB_NAMVANHANH3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_TENCHUNGLOAI4", DbType="NVarChar(500)")]
		public string SC_VTTB_TENCHUNGLOAI4
		{
			get
			{
				return this._SC_VTTB_TENCHUNGLOAI4;
			}
			set
			{
				if ((this._SC_VTTB_TENCHUNGLOAI4 != value))
				{
					this.OnSC_VTTB_TENCHUNGLOAI4Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_TENCHUNGLOAI4 = value;
					this.SendPropertyChanged("SC_VTTB_TENCHUNGLOAI4");
					this.OnSC_VTTB_TENCHUNGLOAI4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_SOLUONG4", DbType="Int")]
		public System.Nullable<int> SC_VTTB_SOLUONG4
		{
			get
			{
				return this._SC_VTTB_SOLUONG4;
			}
			set
			{
				if ((this._SC_VTTB_SOLUONG4 != value))
				{
					this.OnSC_VTTB_SOLUONG4Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_SOLUONG4 = value;
					this.SendPropertyChanged("SC_VTTB_SOLUONG4");
					this.OnSC_VTTB_SOLUONG4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NHASANXUAT4", DbType="NVarChar(500)")]
		public string SC_VTTB_NHASANXUAT4
		{
			get
			{
				return this._SC_VTTB_NHASANXUAT4;
			}
			set
			{
				if ((this._SC_VTTB_NHASANXUAT4 != value))
				{
					this.OnSC_VTTB_NHASANXUAT4Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NHASANXUAT4 = value;
					this.SendPropertyChanged("SC_VTTB_NHASANXUAT4");
					this.OnSC_VTTB_NHASANXUAT4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NAMVANHANH4", DbType="NVarChar(10)")]
		public string SC_VTTB_NAMVANHANH4
		{
			get
			{
				return this._SC_VTTB_NAMVANHANH4;
			}
			set
			{
				if ((this._SC_VTTB_NAMVANHANH4 != value))
				{
					this.OnSC_VTTB_NAMVANHANH4Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NAMVANHANH4 = value;
					this.SendPropertyChanged("SC_VTTB_NAMVANHANH4");
					this.OnSC_VTTB_NAMVANHANH4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_TENCHUNGLOAI5", DbType="NVarChar(500)")]
		public string SC_VTTB_TENCHUNGLOAI5
		{
			get
			{
				return this._SC_VTTB_TENCHUNGLOAI5;
			}
			set
			{
				if ((this._SC_VTTB_TENCHUNGLOAI5 != value))
				{
					this.OnSC_VTTB_TENCHUNGLOAI5Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_TENCHUNGLOAI5 = value;
					this.SendPropertyChanged("SC_VTTB_TENCHUNGLOAI5");
					this.OnSC_VTTB_TENCHUNGLOAI5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_SOLUONG5", DbType="Int")]
		public System.Nullable<int> SC_VTTB_SOLUONG5
		{
			get
			{
				return this._SC_VTTB_SOLUONG5;
			}
			set
			{
				if ((this._SC_VTTB_SOLUONG5 != value))
				{
					this.OnSC_VTTB_SOLUONG5Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_SOLUONG5 = value;
					this.SendPropertyChanged("SC_VTTB_SOLUONG5");
					this.OnSC_VTTB_SOLUONG5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NHASANXUAT5", DbType="NVarChar(500)")]
		public string SC_VTTB_NHASANXUAT5
		{
			get
			{
				return this._SC_VTTB_NHASANXUAT5;
			}
			set
			{
				if ((this._SC_VTTB_NHASANXUAT5 != value))
				{
					this.OnSC_VTTB_NHASANXUAT5Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NHASANXUAT5 = value;
					this.SendPropertyChanged("SC_VTTB_NHASANXUAT5");
					this.OnSC_VTTB_NHASANXUAT5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_VTTB_NAMVANHANH5", DbType="NVarChar(10)")]
		public string SC_VTTB_NAMVANHANH5
		{
			get
			{
				return this._SC_VTTB_NAMVANHANH5;
			}
			set
			{
				if ((this._SC_VTTB_NAMVANHANH5 != value))
				{
					this.OnSC_VTTB_NAMVANHANH5Changing(value);
					this.SendPropertyChanging();
					this._SC_VTTB_NAMVANHANH5 = value;
					this.SendPropertyChanged("SC_VTTB_NAMVANHANH5");
					this.OnSC_VTTB_NAMVANHANH5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SC_THIETBIDONGCAT_MSRCS", DbType="NVarChar(100)")]
		public string SC_THIETBIDONGCAT_MSRCS
		{
			get
			{
				return this._SC_THIETBIDONGCAT_MSRCS;
			}
			set
			{
				if ((this._SC_THIETBIDONGCAT_MSRCS != value))
				{
					this.OnSC_THIETBIDONGCAT_MSRCSChanging(value);
					this.SendPropertyChanging();
					this._SC_THIETBIDONGCAT_MSRCS = value;
					this.SendPropertyChanged("SC_THIETBIDONGCAT_MSRCS");
					this.OnSC_THIETBIDONGCAT_MSRCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLSC_DONVI_QLSC_SUCO", Storage="_QLSC_DONVI", ThisKey="DONVI_ID", OtherKey="DONVI_ID", IsForeignKey=true)]
		public QLSC_DONVI QLSC_DONVI
		{
			get
			{
				return this._QLSC_DONVI.Entity;
			}
			set
			{
				QLSC_DONVI previousValue = this._QLSC_DONVI.Entity;
				if (((previousValue != value) 
							|| (this._QLSC_DONVI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QLSC_DONVI.Entity = null;
						previousValue.QLSC_SUCOs.Remove(this);
					}
					this._QLSC_DONVI.Entity = value;
					if ((value != null))
					{
						value.QLSC_SUCOs.Add(this);
						this._DONVI_ID = value.DONVI_ID;
					}
					else
					{
						this._DONVI_ID = default(int);
					}
					this.SendPropertyChanged("QLSC_DONVI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QLSC_LOAISUCO_QLSC_SUCO", Storage="_QLSC_LOAISUCO", ThisKey="LOAISC_ID", OtherKey="LOAISC_ID", IsForeignKey=true)]
		public QLSC_LOAISUCO QLSC_LOAISUCO
		{
			get
			{
				return this._QLSC_LOAISUCO.Entity;
			}
			set
			{
				QLSC_LOAISUCO previousValue = this._QLSC_LOAISUCO.Entity;
				if (((previousValue != value) 
							|| (this._QLSC_LOAISUCO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QLSC_LOAISUCO.Entity = null;
						previousValue.QLSC_SUCOs.Remove(this);
					}
					this._QLSC_LOAISUCO.Entity = value;
					if ((value != null))
					{
						value.QLSC_SUCOs.Add(this);
						this._LOAISC_ID = value.LOAISC_ID;
					}
					else
					{
						this._LOAISC_ID = default(int);
					}
					this.SendPropertyChanged("QLSC_LOAISUCO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
