#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlhopdong")]
	public partial class QLHDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQLHD_BIEUMAU(QLHD_BIEUMAU instance);
    partial void UpdateQLHD_BIEUMAU(QLHD_BIEUMAU instance);
    partial void DeleteQLHD_BIEUMAU(QLHD_BIEUMAU instance);
    partial void InsertQLHD_TAPTIN(QLHD_TAPTIN instance);
    partial void UpdateQLHD_TAPTIN(QLHD_TAPTIN instance);
    partial void DeleteQLHD_TAPTIN(QLHD_TAPTIN instance);
    partial void InsertQLHD_GIAHANHD(QLHD_GIAHANHD instance);
    partial void UpdateQLHD_GIAHANHD(QLHD_GIAHANHD instance);
    partial void DeleteQLHD_GIAHANHD(QLHD_GIAHANHD instance);
    partial void InsertQLHD_HD(QLHD_HD instance);
    partial void UpdateQLHD_HD(QLHD_HD instance);
    partial void DeleteQLHD_HD(QLHD_HD instance);
    partial void InsertQLHD_LOAIBIEUMAU(QLHD_LOAIBIEUMAU instance);
    partial void UpdateQLHD_LOAIBIEUMAU(QLHD_LOAIBIEUMAU instance);
    partial void DeleteQLHD_LOAIBIEUMAU(QLHD_LOAIBIEUMAU instance);
    #endregion
		
		public QLHDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLHDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QLHD_BIEUMAU> QLHD_BIEUMAUs
		{
			get
			{
				return this.GetTable<QLHD_BIEUMAU>();
			}
		}
		
		public System.Data.Linq.Table<QLHD_TAPTIN> QLHD_TAPTINs
		{
			get
			{
				return this.GetTable<QLHD_TAPTIN>();
			}
		}
		
		public System.Data.Linq.Table<QLHD_GIAHANHD> QLHD_GIAHANHDs
		{
			get
			{
				return this.GetTable<QLHD_GIAHANHD>();
			}
		}
		
		public System.Data.Linq.Table<QLHD_HD> QLHD_HDs
		{
			get
			{
				return this.GetTable<QLHD_HD>();
			}
		}
		
		public System.Data.Linq.Table<QLHD_LOAIBIEUMAU> QLHD_LOAIBIEUMAUs
		{
			get
			{
				return this.GetTable<QLHD_LOAIBIEUMAU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLHD_BIEUMAU")]
	public partial class QLHD_BIEUMAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BM_ID;
		
		private string _BM_TEN;
		
		private string _BM_GHICHU;
		
		private string _BM_TEN_TAPTIN;
		
		private bool _BM_SUDUNG;
		
		private int _LBM_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBM_IDChanging(int value);
    partial void OnBM_IDChanged();
    partial void OnBM_TENChanging(string value);
    partial void OnBM_TENChanged();
    partial void OnBM_GHICHUChanging(string value);
    partial void OnBM_GHICHUChanged();
    partial void OnBM_TEN_TAPTINChanging(string value);
    partial void OnBM_TEN_TAPTINChanged();
    partial void OnBM_SUDUNGChanging(bool value);
    partial void OnBM_SUDUNGChanged();
    partial void OnLBM_IDChanging(int value);
    partial void OnLBM_IDChanged();
    #endregion
		
		public QLHD_BIEUMAU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BM_ID
		{
			get
			{
				return this._BM_ID;
			}
			set
			{
				if ((this._BM_ID != value))
				{
					this.OnBM_IDChanging(value);
					this.SendPropertyChanging();
					this._BM_ID = value;
					this.SendPropertyChanged("BM_ID");
					this.OnBM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM_TEN", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string BM_TEN
		{
			get
			{
				return this._BM_TEN;
			}
			set
			{
				if ((this._BM_TEN != value))
				{
					this.OnBM_TENChanging(value);
					this.SendPropertyChanging();
					this._BM_TEN = value;
					this.SendPropertyChanged("BM_TEN");
					this.OnBM_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM_GHICHU", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BM_GHICHU
		{
			get
			{
				return this._BM_GHICHU;
			}
			set
			{
				if ((this._BM_GHICHU != value))
				{
					this.OnBM_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._BM_GHICHU = value;
					this.SendPropertyChanged("BM_GHICHU");
					this.OnBM_GHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM_TEN_TAPTIN", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string BM_TEN_TAPTIN
		{
			get
			{
				return this._BM_TEN_TAPTIN;
			}
			set
			{
				if ((this._BM_TEN_TAPTIN != value))
				{
					this.OnBM_TEN_TAPTINChanging(value);
					this.SendPropertyChanging();
					this._BM_TEN_TAPTIN = value;
					this.SendPropertyChanged("BM_TEN_TAPTIN");
					this.OnBM_TEN_TAPTINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BM_SUDUNG", DbType="Bit NOT NULL")]
		public bool BM_SUDUNG
		{
			get
			{
				return this._BM_SUDUNG;
			}
			set
			{
				if ((this._BM_SUDUNG != value))
				{
					this.OnBM_SUDUNGChanging(value);
					this.SendPropertyChanging();
					this._BM_SUDUNG = value;
					this.SendPropertyChanged("BM_SUDUNG");
					this.OnBM_SUDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LBM_ID", DbType="Int NOT NULL")]
		public int LBM_ID
		{
			get
			{
				return this._LBM_ID;
			}
			set
			{
				if ((this._LBM_ID != value))
				{
					this.OnLBM_IDChanging(value);
					this.SendPropertyChanging();
					this._LBM_ID = value;
					this.SendPropertyChanged("LBM_ID");
					this.OnLBM_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLHD_TAPTIN")]
	public partial class QLHD_TAPTIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FILE_ID;
		
		private string _FILE_NAME;
		
		private string _FILE_MOTA;
		
		private string _FILE_EXT;
		
		private int _FILE_SIZE;
		
		private int _FILE_USERID_CAPNHAT;
		
		private System.DateTime _FILE_NGAYCAPNHAT;
		
		private int _OBJECT_LOAI;
		
		private int _OBJECT_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFILE_IDChanging(int value);
    partial void OnFILE_IDChanged();
    partial void OnFILE_NAMEChanging(string value);
    partial void OnFILE_NAMEChanged();
    partial void OnFILE_MOTAChanging(string value);
    partial void OnFILE_MOTAChanged();
    partial void OnFILE_EXTChanging(string value);
    partial void OnFILE_EXTChanged();
    partial void OnFILE_SIZEChanging(int value);
    partial void OnFILE_SIZEChanged();
    partial void OnFILE_USERID_CAPNHATChanging(int value);
    partial void OnFILE_USERID_CAPNHATChanged();
    partial void OnFILE_NGAYCAPNHATChanging(System.DateTime value);
    partial void OnFILE_NGAYCAPNHATChanged();
    partial void OnOBJECT_LOAIChanging(int value);
    partial void OnOBJECT_LOAIChanged();
    partial void OnOBJECT_IDChanging(int value);
    partial void OnOBJECT_IDChanged();
    #endregion
		
		public QLHD_TAPTIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FILE_ID
		{
			get
			{
				return this._FILE_ID;
			}
			set
			{
				if ((this._FILE_ID != value))
				{
					this.OnFILE_IDChanging(value);
					this.SendPropertyChanging();
					this._FILE_ID = value;
					this.SendPropertyChanged("FILE_ID");
					this.OnFILE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NAME", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FILE_NAME
		{
			get
			{
				return this._FILE_NAME;
			}
			set
			{
				if ((this._FILE_NAME != value))
				{
					this.OnFILE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FILE_NAME = value;
					this.SendPropertyChanged("FILE_NAME");
					this.OnFILE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_MOTA", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FILE_MOTA
		{
			get
			{
				return this._FILE_MOTA;
			}
			set
			{
				if ((this._FILE_MOTA != value))
				{
					this.OnFILE_MOTAChanging(value);
					this.SendPropertyChanging();
					this._FILE_MOTA = value;
					this.SendPropertyChanged("FILE_MOTA");
					this.OnFILE_MOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_EXT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string FILE_EXT
		{
			get
			{
				return this._FILE_EXT;
			}
			set
			{
				if ((this._FILE_EXT != value))
				{
					this.OnFILE_EXTChanging(value);
					this.SendPropertyChanging();
					this._FILE_EXT = value;
					this.SendPropertyChanged("FILE_EXT");
					this.OnFILE_EXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_SIZE", DbType="Int NOT NULL")]
		public int FILE_SIZE
		{
			get
			{
				return this._FILE_SIZE;
			}
			set
			{
				if ((this._FILE_SIZE != value))
				{
					this.OnFILE_SIZEChanging(value);
					this.SendPropertyChanging();
					this._FILE_SIZE = value;
					this.SendPropertyChanged("FILE_SIZE");
					this.OnFILE_SIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_USERID_CAPNHAT", DbType="Int NOT NULL")]
		public int FILE_USERID_CAPNHAT
		{
			get
			{
				return this._FILE_USERID_CAPNHAT;
			}
			set
			{
				if ((this._FILE_USERID_CAPNHAT != value))
				{
					this.OnFILE_USERID_CAPNHATChanging(value);
					this.SendPropertyChanging();
					this._FILE_USERID_CAPNHAT = value;
					this.SendPropertyChanged("FILE_USERID_CAPNHAT");
					this.OnFILE_USERID_CAPNHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NGAYCAPNHAT", DbType="DateTime NOT NULL")]
		public System.DateTime FILE_NGAYCAPNHAT
		{
			get
			{
				return this._FILE_NGAYCAPNHAT;
			}
			set
			{
				if ((this._FILE_NGAYCAPNHAT != value))
				{
					this.OnFILE_NGAYCAPNHATChanging(value);
					this.SendPropertyChanging();
					this._FILE_NGAYCAPNHAT = value;
					this.SendPropertyChanged("FILE_NGAYCAPNHAT");
					this.OnFILE_NGAYCAPNHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECT_LOAI", DbType="Int NOT NULL")]
		public int OBJECT_LOAI
		{
			get
			{
				return this._OBJECT_LOAI;
			}
			set
			{
				if ((this._OBJECT_LOAI != value))
				{
					this.OnOBJECT_LOAIChanging(value);
					this.SendPropertyChanging();
					this._OBJECT_LOAI = value;
					this.SendPropertyChanged("OBJECT_LOAI");
					this.OnOBJECT_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECT_ID", DbType="Int NOT NULL")]
		public int OBJECT_ID
		{
			get
			{
				return this._OBJECT_ID;
			}
			set
			{
				if ((this._OBJECT_ID != value))
				{
					this.OnOBJECT_IDChanging(value);
					this.SendPropertyChanging();
					this._OBJECT_ID = value;
					this.SendPropertyChanged("OBJECT_ID");
					this.OnOBJECT_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLHD_GIAHANHD")]
	public partial class QLHD_GIAHANHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GIAHAN_ID;
		
		private System.DateTime _HD_HIEULUC_HD;
		
		private System.DateTime _HD_NGAYHETHAN_HD;
		
		private int _HD_TGNHAC;
		
		private System.DateTime _HD_NGAYKHOICONG;
		
		private System.DateTime _HD_NGAYHETHANTHICONG;
		
		private int _HD_THICONG_TGNHAC;
		
		private System.DateTime _HD_BLTHUCHIENHOPDONG_TUNGAY;
		
		private System.DateTime _HD_BLTHUCHIENHOPDONG_DENNGAY;
		
		private int _HD_BLTHUCHIENHOPDONG_TGNHAC;
		
		private System.DateTime _HD_BLTHANHTOANVATTU_TUNGAY;
		
		private System.DateTime _HD_BLTHANHTOANVATTU_DENNGAY;
		
		private int _HD_BLTHANHTOANVATTU_TGNHAC;
		
		private System.DateTime _HD_BLTAMUNG_TUNGAY;
		
		private System.DateTime _HD_BLTAMUNG_DENNGAY;
		
		private int _HD_BLTAMUNG_TGNHAC;
		
		private int _HD_ID;
		
		private string _GIAHAN_GHICHU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGIAHAN_IDChanging(int value);
    partial void OnGIAHAN_IDChanged();
    partial void OnHD_HIEULUC_HDChanging(System.DateTime value);
    partial void OnHD_HIEULUC_HDChanged();
    partial void OnHD_NGAYHETHAN_HDChanging(System.DateTime value);
    partial void OnHD_NGAYHETHAN_HDChanged();
    partial void OnHD_TGNHACChanging(int value);
    partial void OnHD_TGNHACChanged();
    partial void OnHD_NGAYKHOICONGChanging(System.DateTime value);
    partial void OnHD_NGAYKHOICONGChanged();
    partial void OnHD_NGAYHETHANTHICONGChanging(System.DateTime value);
    partial void OnHD_NGAYHETHANTHICONGChanged();
    partial void OnHD_THICONG_TGNHACChanging(int value);
    partial void OnHD_THICONG_TGNHACChanged();
    partial void OnHD_BLTHUCHIENHOPDONG_TUNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHUCHIENHOPDONG_TUNGAYChanged();
    partial void OnHD_BLTHUCHIENHOPDONG_DENNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHUCHIENHOPDONG_DENNGAYChanged();
    partial void OnHD_BLTHUCHIENHOPDONG_TGNHACChanging(int value);
    partial void OnHD_BLTHUCHIENHOPDONG_TGNHACChanged();
    partial void OnHD_BLTHANHTOANVATTU_TUNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHANHTOANVATTU_TUNGAYChanged();
    partial void OnHD_BLTHANHTOANVATTU_DENNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHANHTOANVATTU_DENNGAYChanged();
    partial void OnHD_BLTHANHTOANVATTU_TGNHACChanging(int value);
    partial void OnHD_BLTHANHTOANVATTU_TGNHACChanged();
    partial void OnHD_BLTAMUNG_TUNGAYChanging(System.DateTime value);
    partial void OnHD_BLTAMUNG_TUNGAYChanged();
    partial void OnHD_BLTAMUNG_DENNGAYChanging(System.DateTime value);
    partial void OnHD_BLTAMUNG_DENNGAYChanged();
    partial void OnHD_BLTAMUNG_TGNHACChanging(int value);
    partial void OnHD_BLTAMUNG_TGNHACChanged();
    partial void OnHD_IDChanging(int value);
    partial void OnHD_IDChanged();
    partial void OnGIAHAN_GHICHUChanging(string value);
    partial void OnGIAHAN_GHICHUChanged();
    #endregion
		
		public QLHD_GIAHANHD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAHAN_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GIAHAN_ID
		{
			get
			{
				return this._GIAHAN_ID;
			}
			set
			{
				if ((this._GIAHAN_ID != value))
				{
					this.OnGIAHAN_IDChanging(value);
					this.SendPropertyChanging();
					this._GIAHAN_ID = value;
					this.SendPropertyChanged("GIAHAN_ID");
					this.OnGIAHAN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_HIEULUC_HD", DbType="DateTime NOT NULL")]
		public System.DateTime HD_HIEULUC_HD
		{
			get
			{
				return this._HD_HIEULUC_HD;
			}
			set
			{
				if ((this._HD_HIEULUC_HD != value))
				{
					this.OnHD_HIEULUC_HDChanging(value);
					this.SendPropertyChanging();
					this._HD_HIEULUC_HD = value;
					this.SendPropertyChanged("HD_HIEULUC_HD");
					this.OnHD_HIEULUC_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYHETHAN_HD", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYHETHAN_HD
		{
			get
			{
				return this._HD_NGAYHETHAN_HD;
			}
			set
			{
				if ((this._HD_NGAYHETHAN_HD != value))
				{
					this.OnHD_NGAYHETHAN_HDChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYHETHAN_HD = value;
					this.SendPropertyChanged("HD_NGAYHETHAN_HD");
					this.OnHD_NGAYHETHAN_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_TGNHAC", DbType="Int NOT NULL")]
		public int HD_TGNHAC
		{
			get
			{
				return this._HD_TGNHAC;
			}
			set
			{
				if ((this._HD_TGNHAC != value))
				{
					this.OnHD_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_TGNHAC = value;
					this.SendPropertyChanged("HD_TGNHAC");
					this.OnHD_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYKHOICONG", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYKHOICONG
		{
			get
			{
				return this._HD_NGAYKHOICONG;
			}
			set
			{
				if ((this._HD_NGAYKHOICONG != value))
				{
					this.OnHD_NGAYKHOICONGChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYKHOICONG = value;
					this.SendPropertyChanged("HD_NGAYKHOICONG");
					this.OnHD_NGAYKHOICONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYHETHANTHICONG", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYHETHANTHICONG
		{
			get
			{
				return this._HD_NGAYHETHANTHICONG;
			}
			set
			{
				if ((this._HD_NGAYHETHANTHICONG != value))
				{
					this.OnHD_NGAYHETHANTHICONGChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYHETHANTHICONG = value;
					this.SendPropertyChanged("HD_NGAYHETHANTHICONG");
					this.OnHD_NGAYHETHANTHICONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_THICONG_TGNHAC", DbType="Int NOT NULL")]
		public int HD_THICONG_TGNHAC
		{
			get
			{
				return this._HD_THICONG_TGNHAC;
			}
			set
			{
				if ((this._HD_THICONG_TGNHAC != value))
				{
					this.OnHD_THICONG_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_THICONG_TGNHAC = value;
					this.SendPropertyChanged("HD_THICONG_TGNHAC");
					this.OnHD_THICONG_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHUCHIENHOPDONG_TUNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHUCHIENHOPDONG_TUNGAY
		{
			get
			{
				return this._HD_BLTHUCHIENHOPDONG_TUNGAY;
			}
			set
			{
				if ((this._HD_BLTHUCHIENHOPDONG_TUNGAY != value))
				{
					this.OnHD_BLTHUCHIENHOPDONG_TUNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHUCHIENHOPDONG_TUNGAY = value;
					this.SendPropertyChanged("HD_BLTHUCHIENHOPDONG_TUNGAY");
					this.OnHD_BLTHUCHIENHOPDONG_TUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHUCHIENHOPDONG_DENNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHUCHIENHOPDONG_DENNGAY
		{
			get
			{
				return this._HD_BLTHUCHIENHOPDONG_DENNGAY;
			}
			set
			{
				if ((this._HD_BLTHUCHIENHOPDONG_DENNGAY != value))
				{
					this.OnHD_BLTHUCHIENHOPDONG_DENNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHUCHIENHOPDONG_DENNGAY = value;
					this.SendPropertyChanged("HD_BLTHUCHIENHOPDONG_DENNGAY");
					this.OnHD_BLTHUCHIENHOPDONG_DENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHUCHIENHOPDONG_TGNHAC", DbType="Int NOT NULL")]
		public int HD_BLTHUCHIENHOPDONG_TGNHAC
		{
			get
			{
				return this._HD_BLTHUCHIENHOPDONG_TGNHAC;
			}
			set
			{
				if ((this._HD_BLTHUCHIENHOPDONG_TGNHAC != value))
				{
					this.OnHD_BLTHUCHIENHOPDONG_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHUCHIENHOPDONG_TGNHAC = value;
					this.SendPropertyChanged("HD_BLTHUCHIENHOPDONG_TGNHAC");
					this.OnHD_BLTHUCHIENHOPDONG_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHANHTOANVATTU_TUNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHANHTOANVATTU_TUNGAY
		{
			get
			{
				return this._HD_BLTHANHTOANVATTU_TUNGAY;
			}
			set
			{
				if ((this._HD_BLTHANHTOANVATTU_TUNGAY != value))
				{
					this.OnHD_BLTHANHTOANVATTU_TUNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHANHTOANVATTU_TUNGAY = value;
					this.SendPropertyChanged("HD_BLTHANHTOANVATTU_TUNGAY");
					this.OnHD_BLTHANHTOANVATTU_TUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHANHTOANVATTU_DENNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHANHTOANVATTU_DENNGAY
		{
			get
			{
				return this._HD_BLTHANHTOANVATTU_DENNGAY;
			}
			set
			{
				if ((this._HD_BLTHANHTOANVATTU_DENNGAY != value))
				{
					this.OnHD_BLTHANHTOANVATTU_DENNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHANHTOANVATTU_DENNGAY = value;
					this.SendPropertyChanged("HD_BLTHANHTOANVATTU_DENNGAY");
					this.OnHD_BLTHANHTOANVATTU_DENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHANHTOANVATTU_TGNHAC", DbType="Int NOT NULL")]
		public int HD_BLTHANHTOANVATTU_TGNHAC
		{
			get
			{
				return this._HD_BLTHANHTOANVATTU_TGNHAC;
			}
			set
			{
				if ((this._HD_BLTHANHTOANVATTU_TGNHAC != value))
				{
					this.OnHD_BLTHANHTOANVATTU_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHANHTOANVATTU_TGNHAC = value;
					this.SendPropertyChanged("HD_BLTHANHTOANVATTU_TGNHAC");
					this.OnHD_BLTHANHTOANVATTU_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTAMUNG_TUNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTAMUNG_TUNGAY
		{
			get
			{
				return this._HD_BLTAMUNG_TUNGAY;
			}
			set
			{
				if ((this._HD_BLTAMUNG_TUNGAY != value))
				{
					this.OnHD_BLTAMUNG_TUNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTAMUNG_TUNGAY = value;
					this.SendPropertyChanged("HD_BLTAMUNG_TUNGAY");
					this.OnHD_BLTAMUNG_TUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTAMUNG_DENNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTAMUNG_DENNGAY
		{
			get
			{
				return this._HD_BLTAMUNG_DENNGAY;
			}
			set
			{
				if ((this._HD_BLTAMUNG_DENNGAY != value))
				{
					this.OnHD_BLTAMUNG_DENNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTAMUNG_DENNGAY = value;
					this.SendPropertyChanged("HD_BLTAMUNG_DENNGAY");
					this.OnHD_BLTAMUNG_DENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTAMUNG_TGNHAC", DbType="Int NOT NULL")]
		public int HD_BLTAMUNG_TGNHAC
		{
			get
			{
				return this._HD_BLTAMUNG_TGNHAC;
			}
			set
			{
				if ((this._HD_BLTAMUNG_TGNHAC != value))
				{
					this.OnHD_BLTAMUNG_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTAMUNG_TGNHAC = value;
					this.SendPropertyChanged("HD_BLTAMUNG_TGNHAC");
					this.OnHD_BLTAMUNG_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_ID", DbType="Int NOT NULL")]
		public int HD_ID
		{
			get
			{
				return this._HD_ID;
			}
			set
			{
				if ((this._HD_ID != value))
				{
					this.OnHD_IDChanging(value);
					this.SendPropertyChanging();
					this._HD_ID = value;
					this.SendPropertyChanged("HD_ID");
					this.OnHD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAHAN_GHICHU", DbType="NVarChar(MAX)")]
		public string GIAHAN_GHICHU
		{
			get
			{
				return this._GIAHAN_GHICHU;
			}
			set
			{
				if ((this._GIAHAN_GHICHU != value))
				{
					this.OnGIAHAN_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._GIAHAN_GHICHU = value;
					this.SendPropertyChanged("GIAHAN_GHICHU");
					this.OnGIAHAN_GHICHUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLHD_HD")]
	public partial class QLHD_HD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HD_ID;
		
		private string _HD_TEN;
		
		private string _HD_SO;
		
		private string _HD_TENCONGTRINH;
		
		private System.DateTime _HD_NGAYKY;
		
		private int _HD_THOIGIANTHUCHIEN;
		
		private System.DateTime _HD_HIEULUC_HD;
		
		private System.DateTime _HD_NGAYHETHAN_HD;
		
		private int _HD_TGNHAC;
		
		private decimal _HD_GIATRI;
		
		private string _HD_GHICHU;
		
		private string _HD_TENDONVITHICONG;
		
		private int _HD_THOIGIANTHICONG;
		
		private System.DateTime _HD_NGAYKHOICONG;
		
		private System.DateTime _HD_NGAYHETHANTHICONG;
		
		private int _HD_THICONG_TGNHAC;
		
		private System.DateTime _HD_BLTHUCHIENHOPDONG_TUNGAY;
		
		private System.DateTime _HD_BLTHUCHIENHOPDONG_DENNGAY;
		
		private int _HD_BLTHUCHIENHOPDONG_TGNHAC;
		
		private System.DateTime _HD_BLTHANHTOANVATTU_TUNGAY;
		
		private System.DateTime _HD_BLTHANHTOANVATTU_DENNGAY;
		
		private int _HD_BLTHANHTOANVATTU_TGNHAC;
		
		private System.DateTime _HD_BLTAMUNG_TUNGAY;
		
		private System.DateTime _HD_BLTAMUNG_DENNGAY;
		
		private int _HD_BLTAMUNG_TGNHAC;
		
		private int _HD_TRANGTHAI;
		
		private bool _HD_COGIAHAN;
		
		private bool _HD_XOA;
		
		private int _HD_SOLANGIAHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHD_IDChanging(int value);
    partial void OnHD_IDChanged();
    partial void OnHD_TENChanging(string value);
    partial void OnHD_TENChanged();
    partial void OnHD_SOChanging(string value);
    partial void OnHD_SOChanged();
    partial void OnHD_TENCONGTRINHChanging(string value);
    partial void OnHD_TENCONGTRINHChanged();
    partial void OnHD_NGAYKYChanging(System.DateTime value);
    partial void OnHD_NGAYKYChanged();
    partial void OnHD_THOIGIANTHUCHIENChanging(int value);
    partial void OnHD_THOIGIANTHUCHIENChanged();
    partial void OnHD_HIEULUC_HDChanging(System.DateTime value);
    partial void OnHD_HIEULUC_HDChanged();
    partial void OnHD_NGAYHETHAN_HDChanging(System.DateTime value);
    partial void OnHD_NGAYHETHAN_HDChanged();
    partial void OnHD_TGNHACChanging(int value);
    partial void OnHD_TGNHACChanged();
    partial void OnHD_GIATRIChanging(decimal value);
    partial void OnHD_GIATRIChanged();
    partial void OnHD_GHICHUChanging(string value);
    partial void OnHD_GHICHUChanged();
    partial void OnHD_TENDONVITHICONGChanging(string value);
    partial void OnHD_TENDONVITHICONGChanged();
    partial void OnHD_THOIGIANTHICONGChanging(int value);
    partial void OnHD_THOIGIANTHICONGChanged();
    partial void OnHD_NGAYKHOICONGChanging(System.DateTime value);
    partial void OnHD_NGAYKHOICONGChanged();
    partial void OnHD_NGAYHETHANTHICONGChanging(System.DateTime value);
    partial void OnHD_NGAYHETHANTHICONGChanged();
    partial void OnHD_THICONG_TGNHACChanging(int value);
    partial void OnHD_THICONG_TGNHACChanged();
    partial void OnHD_BLTHUCHIENHOPDONG_TUNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHUCHIENHOPDONG_TUNGAYChanged();
    partial void OnHD_BLTHUCHIENHOPDONG_DENNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHUCHIENHOPDONG_DENNGAYChanged();
    partial void OnHD_BLTHUCHIENHOPDONG_TGNHACChanging(int value);
    partial void OnHD_BLTHUCHIENHOPDONG_TGNHACChanged();
    partial void OnHD_BLTHANHTOANVATTU_TUNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHANHTOANVATTU_TUNGAYChanged();
    partial void OnHD_BLTHANHTOANVATTU_DENNGAYChanging(System.DateTime value);
    partial void OnHD_BLTHANHTOANVATTU_DENNGAYChanged();
    partial void OnHD_BLTHANHTOANVATTU_TGNHACChanging(int value);
    partial void OnHD_BLTHANHTOANVATTU_TGNHACChanged();
    partial void OnHD_BLTAMUNG_TUNGAYChanging(System.DateTime value);
    partial void OnHD_BLTAMUNG_TUNGAYChanged();
    partial void OnHD_BLTAMUNG_DENNGAYChanging(System.DateTime value);
    partial void OnHD_BLTAMUNG_DENNGAYChanged();
    partial void OnHD_BLTAMUNG_TGNHACChanging(int value);
    partial void OnHD_BLTAMUNG_TGNHACChanged();
    partial void OnHD_TRANGTHAIChanging(int value);
    partial void OnHD_TRANGTHAIChanged();
    partial void OnHD_COGIAHANChanging(bool value);
    partial void OnHD_COGIAHANChanged();
    partial void OnHD_XOAChanging(bool value);
    partial void OnHD_XOAChanged();
    partial void OnHD_SOLANGIAHANChanging(int value);
    partial void OnHD_SOLANGIAHANChanged();
    #endregion
		
		public QLHD_HD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HD_ID
		{
			get
			{
				return this._HD_ID;
			}
			set
			{
				if ((this._HD_ID != value))
				{
					this.OnHD_IDChanging(value);
					this.SendPropertyChanging();
					this._HD_ID = value;
					this.SendPropertyChanged("HD_ID");
					this.OnHD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_TEN", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HD_TEN
		{
			get
			{
				return this._HD_TEN;
			}
			set
			{
				if ((this._HD_TEN != value))
				{
					this.OnHD_TENChanging(value);
					this.SendPropertyChanging();
					this._HD_TEN = value;
					this.SendPropertyChanged("HD_TEN");
					this.OnHD_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_SO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HD_SO
		{
			get
			{
				return this._HD_SO;
			}
			set
			{
				if ((this._HD_SO != value))
				{
					this.OnHD_SOChanging(value);
					this.SendPropertyChanging();
					this._HD_SO = value;
					this.SendPropertyChanged("HD_SO");
					this.OnHD_SOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_TENCONGTRINH", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HD_TENCONGTRINH
		{
			get
			{
				return this._HD_TENCONGTRINH;
			}
			set
			{
				if ((this._HD_TENCONGTRINH != value))
				{
					this.OnHD_TENCONGTRINHChanging(value);
					this.SendPropertyChanging();
					this._HD_TENCONGTRINH = value;
					this.SendPropertyChanged("HD_TENCONGTRINH");
					this.OnHD_TENCONGTRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYKY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYKY
		{
			get
			{
				return this._HD_NGAYKY;
			}
			set
			{
				if ((this._HD_NGAYKY != value))
				{
					this.OnHD_NGAYKYChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYKY = value;
					this.SendPropertyChanged("HD_NGAYKY");
					this.OnHD_NGAYKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_THOIGIANTHUCHIEN", DbType="Int NOT NULL")]
		public int HD_THOIGIANTHUCHIEN
		{
			get
			{
				return this._HD_THOIGIANTHUCHIEN;
			}
			set
			{
				if ((this._HD_THOIGIANTHUCHIEN != value))
				{
					this.OnHD_THOIGIANTHUCHIENChanging(value);
					this.SendPropertyChanging();
					this._HD_THOIGIANTHUCHIEN = value;
					this.SendPropertyChanged("HD_THOIGIANTHUCHIEN");
					this.OnHD_THOIGIANTHUCHIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_HIEULUC_HD", DbType="DateTime NOT NULL")]
		public System.DateTime HD_HIEULUC_HD
		{
			get
			{
				return this._HD_HIEULUC_HD;
			}
			set
			{
				if ((this._HD_HIEULUC_HD != value))
				{
					this.OnHD_HIEULUC_HDChanging(value);
					this.SendPropertyChanging();
					this._HD_HIEULUC_HD = value;
					this.SendPropertyChanged("HD_HIEULUC_HD");
					this.OnHD_HIEULUC_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYHETHAN_HD", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYHETHAN_HD
		{
			get
			{
				return this._HD_NGAYHETHAN_HD;
			}
			set
			{
				if ((this._HD_NGAYHETHAN_HD != value))
				{
					this.OnHD_NGAYHETHAN_HDChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYHETHAN_HD = value;
					this.SendPropertyChanged("HD_NGAYHETHAN_HD");
					this.OnHD_NGAYHETHAN_HDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_TGNHAC", DbType="Int NOT NULL")]
		public int HD_TGNHAC
		{
			get
			{
				return this._HD_TGNHAC;
			}
			set
			{
				if ((this._HD_TGNHAC != value))
				{
					this.OnHD_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_TGNHAC = value;
					this.SendPropertyChanged("HD_TGNHAC");
					this.OnHD_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_GIATRI", DbType="Decimal(18,0) NOT NULL")]
		public decimal HD_GIATRI
		{
			get
			{
				return this._HD_GIATRI;
			}
			set
			{
				if ((this._HD_GIATRI != value))
				{
					this.OnHD_GIATRIChanging(value);
					this.SendPropertyChanging();
					this._HD_GIATRI = value;
					this.SendPropertyChanged("HD_GIATRI");
					this.OnHD_GIATRIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_GHICHU", DbType="NVarChar(MAX)")]
		public string HD_GHICHU
		{
			get
			{
				return this._HD_GHICHU;
			}
			set
			{
				if ((this._HD_GHICHU != value))
				{
					this.OnHD_GHICHUChanging(value);
					this.SendPropertyChanging();
					this._HD_GHICHU = value;
					this.SendPropertyChanged("HD_GHICHU");
					this.OnHD_GHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_TENDONVITHICONG", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HD_TENDONVITHICONG
		{
			get
			{
				return this._HD_TENDONVITHICONG;
			}
			set
			{
				if ((this._HD_TENDONVITHICONG != value))
				{
					this.OnHD_TENDONVITHICONGChanging(value);
					this.SendPropertyChanging();
					this._HD_TENDONVITHICONG = value;
					this.SendPropertyChanged("HD_TENDONVITHICONG");
					this.OnHD_TENDONVITHICONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_THOIGIANTHICONG", DbType="Int NOT NULL")]
		public int HD_THOIGIANTHICONG
		{
			get
			{
				return this._HD_THOIGIANTHICONG;
			}
			set
			{
				if ((this._HD_THOIGIANTHICONG != value))
				{
					this.OnHD_THOIGIANTHICONGChanging(value);
					this.SendPropertyChanging();
					this._HD_THOIGIANTHICONG = value;
					this.SendPropertyChanged("HD_THOIGIANTHICONG");
					this.OnHD_THOIGIANTHICONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYKHOICONG", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYKHOICONG
		{
			get
			{
				return this._HD_NGAYKHOICONG;
			}
			set
			{
				if ((this._HD_NGAYKHOICONG != value))
				{
					this.OnHD_NGAYKHOICONGChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYKHOICONG = value;
					this.SendPropertyChanged("HD_NGAYKHOICONG");
					this.OnHD_NGAYKHOICONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_NGAYHETHANTHICONG", DbType="DateTime NOT NULL")]
		public System.DateTime HD_NGAYHETHANTHICONG
		{
			get
			{
				return this._HD_NGAYHETHANTHICONG;
			}
			set
			{
				if ((this._HD_NGAYHETHANTHICONG != value))
				{
					this.OnHD_NGAYHETHANTHICONGChanging(value);
					this.SendPropertyChanging();
					this._HD_NGAYHETHANTHICONG = value;
					this.SendPropertyChanged("HD_NGAYHETHANTHICONG");
					this.OnHD_NGAYHETHANTHICONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_THICONG_TGNHAC", DbType="Int NOT NULL")]
		public int HD_THICONG_TGNHAC
		{
			get
			{
				return this._HD_THICONG_TGNHAC;
			}
			set
			{
				if ((this._HD_THICONG_TGNHAC != value))
				{
					this.OnHD_THICONG_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_THICONG_TGNHAC = value;
					this.SendPropertyChanged("HD_THICONG_TGNHAC");
					this.OnHD_THICONG_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHUCHIENHOPDONG_TUNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHUCHIENHOPDONG_TUNGAY
		{
			get
			{
				return this._HD_BLTHUCHIENHOPDONG_TUNGAY;
			}
			set
			{
				if ((this._HD_BLTHUCHIENHOPDONG_TUNGAY != value))
				{
					this.OnHD_BLTHUCHIENHOPDONG_TUNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHUCHIENHOPDONG_TUNGAY = value;
					this.SendPropertyChanged("HD_BLTHUCHIENHOPDONG_TUNGAY");
					this.OnHD_BLTHUCHIENHOPDONG_TUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHUCHIENHOPDONG_DENNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHUCHIENHOPDONG_DENNGAY
		{
			get
			{
				return this._HD_BLTHUCHIENHOPDONG_DENNGAY;
			}
			set
			{
				if ((this._HD_BLTHUCHIENHOPDONG_DENNGAY != value))
				{
					this.OnHD_BLTHUCHIENHOPDONG_DENNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHUCHIENHOPDONG_DENNGAY = value;
					this.SendPropertyChanged("HD_BLTHUCHIENHOPDONG_DENNGAY");
					this.OnHD_BLTHUCHIENHOPDONG_DENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHUCHIENHOPDONG_TGNHAC", DbType="Int NOT NULL")]
		public int HD_BLTHUCHIENHOPDONG_TGNHAC
		{
			get
			{
				return this._HD_BLTHUCHIENHOPDONG_TGNHAC;
			}
			set
			{
				if ((this._HD_BLTHUCHIENHOPDONG_TGNHAC != value))
				{
					this.OnHD_BLTHUCHIENHOPDONG_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHUCHIENHOPDONG_TGNHAC = value;
					this.SendPropertyChanged("HD_BLTHUCHIENHOPDONG_TGNHAC");
					this.OnHD_BLTHUCHIENHOPDONG_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHANHTOANVATTU_TUNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHANHTOANVATTU_TUNGAY
		{
			get
			{
				return this._HD_BLTHANHTOANVATTU_TUNGAY;
			}
			set
			{
				if ((this._HD_BLTHANHTOANVATTU_TUNGAY != value))
				{
					this.OnHD_BLTHANHTOANVATTU_TUNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHANHTOANVATTU_TUNGAY = value;
					this.SendPropertyChanged("HD_BLTHANHTOANVATTU_TUNGAY");
					this.OnHD_BLTHANHTOANVATTU_TUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHANHTOANVATTU_DENNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTHANHTOANVATTU_DENNGAY
		{
			get
			{
				return this._HD_BLTHANHTOANVATTU_DENNGAY;
			}
			set
			{
				if ((this._HD_BLTHANHTOANVATTU_DENNGAY != value))
				{
					this.OnHD_BLTHANHTOANVATTU_DENNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHANHTOANVATTU_DENNGAY = value;
					this.SendPropertyChanged("HD_BLTHANHTOANVATTU_DENNGAY");
					this.OnHD_BLTHANHTOANVATTU_DENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTHANHTOANVATTU_TGNHAC", DbType="Int NOT NULL")]
		public int HD_BLTHANHTOANVATTU_TGNHAC
		{
			get
			{
				return this._HD_BLTHANHTOANVATTU_TGNHAC;
			}
			set
			{
				if ((this._HD_BLTHANHTOANVATTU_TGNHAC != value))
				{
					this.OnHD_BLTHANHTOANVATTU_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTHANHTOANVATTU_TGNHAC = value;
					this.SendPropertyChanged("HD_BLTHANHTOANVATTU_TGNHAC");
					this.OnHD_BLTHANHTOANVATTU_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTAMUNG_TUNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTAMUNG_TUNGAY
		{
			get
			{
				return this._HD_BLTAMUNG_TUNGAY;
			}
			set
			{
				if ((this._HD_BLTAMUNG_TUNGAY != value))
				{
					this.OnHD_BLTAMUNG_TUNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTAMUNG_TUNGAY = value;
					this.SendPropertyChanged("HD_BLTAMUNG_TUNGAY");
					this.OnHD_BLTAMUNG_TUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTAMUNG_DENNGAY", DbType="DateTime NOT NULL")]
		public System.DateTime HD_BLTAMUNG_DENNGAY
		{
			get
			{
				return this._HD_BLTAMUNG_DENNGAY;
			}
			set
			{
				if ((this._HD_BLTAMUNG_DENNGAY != value))
				{
					this.OnHD_BLTAMUNG_DENNGAYChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTAMUNG_DENNGAY = value;
					this.SendPropertyChanged("HD_BLTAMUNG_DENNGAY");
					this.OnHD_BLTAMUNG_DENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_BLTAMUNG_TGNHAC", DbType="Int NOT NULL")]
		public int HD_BLTAMUNG_TGNHAC
		{
			get
			{
				return this._HD_BLTAMUNG_TGNHAC;
			}
			set
			{
				if ((this._HD_BLTAMUNG_TGNHAC != value))
				{
					this.OnHD_BLTAMUNG_TGNHACChanging(value);
					this.SendPropertyChanging();
					this._HD_BLTAMUNG_TGNHAC = value;
					this.SendPropertyChanged("HD_BLTAMUNG_TGNHAC");
					this.OnHD_BLTAMUNG_TGNHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_TRANGTHAI", DbType="Int NOT NULL")]
		public int HD_TRANGTHAI
		{
			get
			{
				return this._HD_TRANGTHAI;
			}
			set
			{
				if ((this._HD_TRANGTHAI != value))
				{
					this.OnHD_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._HD_TRANGTHAI = value;
					this.SendPropertyChanged("HD_TRANGTHAI");
					this.OnHD_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_COGIAHAN", DbType="Bit NOT NULL")]
		public bool HD_COGIAHAN
		{
			get
			{
				return this._HD_COGIAHAN;
			}
			set
			{
				if ((this._HD_COGIAHAN != value))
				{
					this.OnHD_COGIAHANChanging(value);
					this.SendPropertyChanging();
					this._HD_COGIAHAN = value;
					this.SendPropertyChanged("HD_COGIAHAN");
					this.OnHD_COGIAHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_XOA", DbType="Bit NOT NULL")]
		public bool HD_XOA
		{
			get
			{
				return this._HD_XOA;
			}
			set
			{
				if ((this._HD_XOA != value))
				{
					this.OnHD_XOAChanging(value);
					this.SendPropertyChanging();
					this._HD_XOA = value;
					this.SendPropertyChanged("HD_XOA");
					this.OnHD_XOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HD_SOLANGIAHAN", DbType="Int NOT NULL")]
		public int HD_SOLANGIAHAN
		{
			get
			{
				return this._HD_SOLANGIAHAN;
			}
			set
			{
				if ((this._HD_SOLANGIAHAN != value))
				{
					this.OnHD_SOLANGIAHANChanging(value);
					this.SendPropertyChanging();
					this._HD_SOLANGIAHAN = value;
					this.SendPropertyChanged("HD_SOLANGIAHAN");
					this.OnHD_SOLANGIAHANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QLHD_LOAIBIEUMAU")]
	public partial class QLHD_LOAIBIEUMAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LBM_ID;
		
		private string _LBM_TEN;
		
		private string _LBM_MOTA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLBM_IDChanging(int value);
    partial void OnLBM_IDChanged();
    partial void OnLBM_TENChanging(string value);
    partial void OnLBM_TENChanged();
    partial void OnLBM_MOTAChanging(string value);
    partial void OnLBM_MOTAChanged();
    #endregion
		
		public QLHD_LOAIBIEUMAU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LBM_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LBM_ID
		{
			get
			{
				return this._LBM_ID;
			}
			set
			{
				if ((this._LBM_ID != value))
				{
					this.OnLBM_IDChanging(value);
					this.SendPropertyChanging();
					this._LBM_ID = value;
					this.SendPropertyChanged("LBM_ID");
					this.OnLBM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LBM_TEN", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string LBM_TEN
		{
			get
			{
				return this._LBM_TEN;
			}
			set
			{
				if ((this._LBM_TEN != value))
				{
					this.OnLBM_TENChanging(value);
					this.SendPropertyChanging();
					this._LBM_TEN = value;
					this.SendPropertyChanged("LBM_TEN");
					this.OnLBM_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LBM_MOTA", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LBM_MOTA
		{
			get
			{
				return this._LBM_MOTA;
			}
			set
			{
				if ((this._LBM_MOTA != value))
				{
					this.OnLBM_MOTAChanging(value);
					this.SendPropertyChanging();
					this._LBM_MOTA = value;
					this.SendPropertyChanged("LBM_MOTA");
					this.OnLBM_MOTAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
