<?xml version="1.0" encoding="utf-8"?><Database Name="qlhopdong" Class="QLHDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=qlhopdong;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QLHD_BIEUMAU" Member="QLHD_BIEUMAUs">
    <Type Name="QLHD_BIEUMAU">
      <Column Name="BM_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BM_TEN" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BM_GHICHU" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BM_TEN_TAPTIN" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BM_SUDUNG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LBM_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QLHD_TAPTIN" Member="QLHD_TAPTINs">
    <Type Name="QLHD_TAPTIN">
      <Column Name="FILE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FILE_NAME" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FILE_MOTA" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="FILE_EXT" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="FILE_SIZE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FILE_USERID_CAPNHAT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FILE_NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OBJECT_LOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OBJECT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QLHD_GIAHANHD" Member="QLHD_GIAHANHDs">
    <Type Name="QLHD_GIAHANHD">
      <Column Name="GIAHAN_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HD_HIEULUC_HD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYHETHAN_HD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYKHOICONG" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYHETHANTHICONG" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_THICONG_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHUCHIENHOPDONG_TUNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHUCHIENHOPDONG_DENNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHUCHIENHOPDONG_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHANHTOANVATTU_TUNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHANHTOANVATTU_DENNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHANHTOANVATTU_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTAMUNG_TUNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTAMUNG_DENNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTAMUNG_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIAHAN_GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QLHD_HD" Member="QLHD_HDs">
    <Type Name="QLHD_HD">
      <Column Name="HD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HD_TEN" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HD_SO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HD_TENCONGTRINH" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYKY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_THOIGIANTHUCHIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_HIEULUC_HD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYHETHAN_HD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_GIATRI" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="HD_GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HD_TENDONVITHICONG" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HD_THOIGIANTHICONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYKHOICONG" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_NGAYHETHANTHICONG" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_THICONG_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHUCHIENHOPDONG_TUNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHUCHIENHOPDONG_DENNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHUCHIENHOPDONG_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHANHTOANVATTU_TUNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHANHTOANVATTU_DENNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTHANHTOANVATTU_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTAMUNG_TUNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTAMUNG_DENNGAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HD_BLTAMUNG_TGNHAC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_TRANGTHAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HD_COGIAHAN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HD_XOA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HD_SOLANGIAHAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QLHD_LOAIBIEUMAU" Member="QLHD_LOAIBIEUMAUs">
    <Type Name="QLHD_LOAIBIEUMAU">
      <Column Name="LBM_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LBM_TEN" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LBM_MOTA" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>